INSERT INTO `managers` (`id`, `name`, `password`) VALUES (1, '邓云熙', 'D70TdNRkIP');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (2, 'Walter Rose', 'xj8TucMjtL');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (3, '郝致远', 'yJ0als5xbB');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (4, '佐野詩乃', 'l16dIMNAqY');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (5, '杉山百恵', 'XBqGNqAjNu');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (6, 'Ruth Gonzalez', '8frBdYJLy1');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (7, '贾睿', 'i4t97t9Gla');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (8, '斎藤樹', 'JKpr5OAajF');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (9, '朱晓明', 'IUmpfi8hw8');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (10, '冯璐', 'DTLWkoPif9');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (11, '萧安琪', 'VZvIfQcSyu');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (12, 'Debbie Crawford', 'x9G0j5iaC3');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (13, 'Roger Reyes', 'dQ2OPnS3xA');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (14, 'Sheila Reed', 'iHpgu2yrWI');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (15, 'Bobby Brooks', '0iD6wa916h');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (16, '谭云熙', 'WgkoeZmfr5');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (17, '松井涼太', 'd96pjhpxYz');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (18, '夏安琪', '0FsgW5kfXn');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (19, 'Larry Barnes', 'TePo33snJE');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (20, '遠藤桜', 'WTvvRizeeB');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (21, '鈴木葵', 'rL9n66gQP2');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (22, '蒋岚', 'vedHpEWy6p');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (23, 'Ronald Carter', 'u4yHiTiOEA');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (24, '严岚', 'SvQ8djyHGS');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (25, '山崎紗良', '7X8vgP4mZ5');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (26, 'Travis Martin', '5M4d03rCoe');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (27, 'Monica Rogers', 'HBdWM2fExH');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (28, 'Juan Baker', 'cqqAE22AGI');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (29, '石田大地', 'y2yWRAcGj6');
INSERT INTO `managers` (`id`, `name`, `password`) VALUES (30, '中村聖子', 'e3QbwVcucY');
